import React from 'react';

const TermsOfService = () => {
  const websiteUrl = window.location.origin;

  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 selection:bg-primary-500/30 p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
        <p className="text-slate-400 mb-4">Last updated: November 23, 2025</p>
        <div className="prose prose-invert">
          <p>Please read these Terms of Service carefully before using our website, <a href={websiteUrl} className="text-primary-400">{websiteUrl}</a>. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.</p>
          <h2 className="text-2xl font-bold mt-8 mb-4">AI-Generated Content</h2>
          <p>The content on this website is generated by artificial intelligence. We do not make any warranties about the completeness, reliability, and accuracy of this information. Any action you take upon the information you find on this website is strictly at your own risk. AlgoMap AI will not be liable for any losses and/or damages in connection with the use of our website.</p>
          <h2 className="text-2xl font-bold mt-8 mb-4">Intellectual Property</h2>
          <p>The Service and its original content, features, and functionality are and will remain the exclusive property of AlgoMap AI and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of AlgoMap AI.</p>
          <h2 className="text-2xl font-bold mt-8 mb-4">Limitation of Liability</h2>
          <p>In no event shall AlgoMap AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
          <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at <a href="mailto:maddalajashwanth69@gmail.com" className="text-primary-400">maddalajashwanth69@gmail.com</a>.</p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
